YOUTUBE_PLAYLIST_IDS = [
    ("Philip Maloney und der Weihnachtsmann (Teil 1 & Teil 2)", "OLAK5uy_nDxcA21mvs41Ho7MFnborFXbbCGzXBKgE"),
    ("GRAF, R.: Haarsträubenden Fälle des Philip Maloney (Die), Vol. 1", "OLAK5uy_n5FDWTaha7G110QR37SVkIz5YDy_biD4Q"),
    ("GRAF, R.: Haarsträubenden Fälle des Philip Maloney (Die), Vol. 2", "OLAK5uy_l3FVNqPk6jDZrzqlJ1WBannctleSPOA3k"),
    ("GRAF, R.: Haarsträubenden Fälle des Philip Maloney (Die), Vol. 3", "OLAK5uy_mHvyJsGzoqjbsYkx5pevoZja1bFJJmDeQ"),
    ("Die haarsträubenden Fälle des Philip Maloney, Vol. 4", "OLAK5uy_lwhuEv78nEkxubk9k1vUlMTtU89aO_g7I"),
    ("Die haarsträubenden Fälle des Philip Maloney, Vol. 5", "OLAK5uy_mRIO2Zy5TTxwTLcRCS4nSDa-4w0eapZhc"),
    ("Die haarsträubenden Fälle des Philip Maloney, Vol. 6", "OLAK5uy_moHj3raDL-GvmMqaWwvDdPe1wJZGy__Rg"),
    ("Die haarsträubenden Fälle des Philip Maloney Vol. 7", "OLAK5uy_m5V_SIRFrDJAxjlEzBs9sRKwNzqmUiTRo"),
    ("Die haarsträubenden Fälle des Philip Maloney, Vol. 8", "OLAK5uy_k44bBkxY04YEK_-9_GpbywtE3t_8yGnmc"),
    ("GRAF, R.: Haarsträubenden Fälle des Philip Maloney (Die), Vol. 9", "OLAK5uy_mFVQrrjorpwuqR_MKYTWUMcUAE_xWcjQk"),
    ("Die haarsträubenden Fälle des Philip Maloney, Vol. 10", "OLAK5uy_kw65IvEZjKN0kMbY_qXBwQbqlRXzhxugA"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.13 (Der Tote im Park, Der Ernstfall, Die Erstausgabe, Die Terrasse)", "OLAK5uy_n3XNKv00g6JkdQ2xETQqJKGcUK2Gc9LlI"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.14 (Der verlorene Sohn, Der Entführte, Die Verfolgte, Jackpot)", "OLAK5uy_mm7I0frNfyOXm1qhpeixr2WAZRXZTGdwg"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.15 (Mord nach Noten, Schwedische Gardinen, Das achte Loch, Schwarz auf Weiss)", "OLAK5uy_k1qFUVeQE9dArSuyN3AuLcF0-6Z4AGvr8"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.16 (Das hohe Fenster, Der lange Abschied, Die Dame im See, Leb wohl, mein Liebling)", "OLAK5uy_lZytTT5K3J6y27WaiW5wz3oyFZBcMLxL4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.17 (Wien bei Nacht, Die unsichtbare Leiche, Hopfen und Malz, Der Blockwart)", "OLAK5uy_nnt8FHLIMvm9ynxR3Rpy8A5JxkJ-r0vYA"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.18 (Die Laube, Das Ohr des Meisters, Die andere Frau, Ein seltsames Paar)", "OLAK5uy_n9qjuq3Eu6Us1gunagxOnEXbgALFMhSlM"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.19 (Der schwarze Koffer, Der Knall, Seltsame Vögel, Seemannsgarn)", "OLAK5uy_k-wWyXfSeLlx2Q8xu8NnYKZMANo-4Gsng"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.20 (Das Sommerloch, Abgereist ohne Adressangabe, Der grosse Schlaf, Fahrt ins Blaue)", "OLAK5uy_mPOssSl7ZSjr1TD5BqHGE-fflCpA1Lar4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.21 (Tödliche Ausstellung, Dunkle Geschäfte, Schadenfreude)", "OLAK5uy_mwFKjPrQlINbO1nPLVRvuioJERt18DiTI"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.22 (Der Stein der Weisen, Der Heiratsschwindler, Der Goldfisch)", "OLAK5uy_lv17JNW2fK5W6GmKJ_Q8oCq2OG0WGS7rg"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.23 (Der Anfänger, Das Anwaltsgeheimnis, Die Armbanduhr)", "OLAK5uy_kxALbE5w6drzN-BaPWBwezgH6-Zs0fucc"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.24 (Der Mörderhai, Druckbuchstaben, Der Wettkampf)", "OLAK5uy_kkco-LbWpJ5YHARWQMAReIquhOqxD5Dro"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.25 (Der liebe Onkel, Die Handtasche, Auf der Flucht)", "OLAK5uy_ngyafJZA8iifviA5ldm94uQjDq21irsn4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.26 (Heisse Tage, Durch dick und dünn, Suchtgefahr)", "OLAK5uy_ljUxFznQ5HCqDlnXcpYZScz20ulj57rp8"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.27 (Klopfzeichen, Der Händler, Fälschungen)", "OLAK5uy_kxjNYRDv8Osg383D3h4ijNoBU-KgPEUKc"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.28 (Die nassen Hosen, Die Lösung, Aus heiterem Himmel)", "OLAK5uy_kja8-RB2TH4Z3jnqXBPq7rO6Qjo8pgzn4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.29 (Das trojanische Pferd, Tod eines Baulöwen, Die kleine Schwester)", "OLAK5uy_lRP_suA_s8WqlIiXqsnyz_r9TuQKAnDqE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.30 (Das Geschäftsessen, Der Feuerteufel, Playback)", "OLAK5uy_kOqu9rr9eM8t2dGu8abgMiPuV4qmFGEwg"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.31 (Die Nacht der langen Messer, Blind Date, Das Sommerrätsel)", "OLAK5uy_nMdYVxbBjOVKLhXTC1IyLKIUtMUA_4oe4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.32 (Das Hausfest, Hundstage, Garten des Todes)", "OLAK5uy_nkUXpkb82c8HpCdk2r9dlhXE68CbJtyn0"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.33 (Das Appartement, Galerie der Toten, Kunstfehler)", "OLAK5uy_nc9YxfLVrf9FxOrY7kBDCq6EV-w0y-Dnw"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.34 (Zur Hölle mit Don Giovanni, Die blaue Tasche, Die Spätvorstellung)", "OLAK5uy_nfStIgvxWD946a-QOVO1lfR0Rfwyy22Bo"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.35 (Der grosse Knall, Der Doppelgänger, Der Postraub)", "OLAK5uy_nLhjvdsZQ3pR36hqedscdOZD6B2_tGc64"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.36 (Der Angler, Das Versprechen, Das andere Leben)", "OLAK5uy_kOCxM16QYwAO7O6CaE7PHj07GZMfU5vh4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.37 (Lange Nächte, Mord nach Plan, Der Weg nach oben)", "OLAK5uy_k1oct3wfbnIQM86NDdXsN--Ejm-h_Yk9Y"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.38 (Seltsame Zeugen, Der Ball ist rund, Der Womper)", "OLAK5uy_nzMFY90aaWjV8ipVxZkLbV9M27dvMyPSw"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.39 (Schüsse im Äther, Der direkte Draht, Das Portrait)", "OLAK5uy_le1TZQQUG36SiY7Xw_cPMAHwfcdnRBs-o"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.40 (Rollenspiel, Das Rattennest, Schöne Bescherung)", "OLAK5uy_kbTaqbT2NJ8eix_hNLoME_-635BlmwEh4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.41 (Die Hand, Ein tierischer Verdacht, Der Geheimdienst)", "OLAK5uy_lMZHHwRWSZFTDXIVr2TxdhleggZQUwZuQ"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.42 (Das stille Örtchen, Die Bombenbastler, Der Banküberfall)", "OLAK5uy_kYwPOyvFc4FAJrUs4xNXurYsRkqW8inUo"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.43 (Das Erbe, Der Grabstein, Ein friedlicher Park)", "OLAK5uy_mC2O-flhc-WF11K8_0crvOBFYei_qwOCY"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.44 (Das Jubiläum, Das Seminar, Die Dämonen)", "OLAK5uy_nk6kisBWIsgqhLN7d-j19ifdCWorEjWb8"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.45 (Das Künstlerheim, Durch die Blume, Mord im Parkhaus)", "OLAK5uy_npxn5zCXF3Prb_m0Gu9la6lvKHYNvSifs"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.46 (23 Rosen, Der Test, Die Agenda)", "OLAK5uy_kziZTnwRjkESW9tD4VqiwZ-x5LpQ2bVJE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.47 (Der Mann im Hotel, Die Mondfinsternis, Die Saisonkarte)", "OLAK5uy_n9UVSYJyvAZ9b-kZxVn1herwgKDQIWKtk"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.48 (Der Elsternverein, Der falsche Hund, Der Fasnachtsmörder)", "OLAK5uy_kJnbTKlGo-OmDsiA_S8t_8xEMrkdTjG-o"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.49 (Das Comeback, Die fremde Wohnung, Die Alters-WG)", "OLAK5uy_nMYV9vyoCAQd3ZBC8fgC2cwxSXVwqoJkE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.50 (Das doppelte Leben, Die Ferienbekanntschaft, Der Tramkiller)", "OLAK5uy_k1hNFraHRvlG2XG0zf1VYDmvk8CHNBSNE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.51 (Der blaue Dunst, Die Bedrohung, Der Höhlenmensch)", "OLAK5uy_mYxwtGhGaCYdvJxQqZ8X5n0VCvSIDKKvU"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.52 (Tod im Schnee, Die Beute, Zum Kuckuck)", "OLAK5uy_nbqXwW6GkkWt8SC1VIjKtbk30WKOgCE1Y"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.53 (Die Farbtherapie, Tod eines Architekten, Der Fremde)", "OLAK5uy_n3Zj-cjOJAqyKUIiL6MQsY13x8mqJpc9s"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.54 (Eiszeit, Mord im Theater, Der Bootsausflug)", "OLAK5uy_nZ0i7Ly_dbqqlHZwDT5ykNVVhIbiJsBYA"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.55 (Das Nebeneinkommen, Der Schatten, Der Geizhals)", "OLAK5uy_knLIviP66JmExadL0hZObPfGMWcrAGkss"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.56 (Der schöne Fuss, Die Dichterlesung, Tödliches Frühstück)", "OLAK5uy_l4VoVURU0DJA7zltB9zhE5Z1Vr50uRR3w"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.57 (Blitz und Donner, Das zweite Ich, Der Bodybuilder)", "OLAK5uy_mrZLEx-nLTRUgURck-0POlaTeoYqy3DK0"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.58 (Fanpost, Geisterstunde, Trickdiebe)", "OLAK5uy_nmfD5Lcw2FMb0Gk9a2b_bmIAx_hPtbLvM"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.59 (Das Rennpferd, Die Einbrecherin, Hirngespinste)", "OLAK5uy_mcPXq0kP_J4aV7P9m-lI5dqSP3pqaPuqE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.60 (Das Investment, Der Jungbrunnen, Die verschwundenen Trucks)", "OLAK5uy_lbh28KrBn2ixc2vPGWxH1qfD79JH05PTM"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.61 (Das Freudenhaus, Der Baum, Die Milleniumsleiche)", "OLAK5uy_kf9jzlcpm7RJWKbthXLHZu4JKHuhj3InA"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.62 (Das Feuerwerk, Nachbarschaftshilfe, Tiefdruckgebiete)", "OLAK5uy_mcZR8yyfaeQLUbEQa7gmeN3pC-F05N8yI"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.63 (Der Autodieb, Der Sprayer, Der Vorleser)", "OLAK5uy_mo7VrO_s3pCE6A2NdOwMoYao1ekRuCcl0"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.64 (Billy the Kid, Der Raubüberfall, Tödliches Spiel)", "OLAK5uy_lqqMi8giq9FGktwgBlAbTnxoN-5-opDZk"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.65 (Der Schlüssel, Die lieben Nachbarn, Oh Tannenbaum)", "OLAK5uy_nvpixbJfzinOQ8qi1hfMgoZGFEfcBFsnc"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.66 (Der Bestseller, Der Matador, Marsmenschen)", "OLAK5uy_n0bL5UqCBB3Hu1bJ0hVfeNc2_zySl6CPw"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.67 (Das Erlebnishotel, Das Kaffeekränzchen, Von Quoten und Toten)", "OLAK5uy_m9j9bZ00EiiQUBiVy8CPopHwpa1fwIvKw"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.68 (Der Teddybär, Die Schlafwandlerin, Die Tonjäger)", "OLAK5uy_m2IYfJl9ug_CUbe7mu-WoESRjy1Z6cf-I"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.69 (Der Hellseher, Haarige Zeiten, Schmuckstücke)", "OLAK5uy_k6bZQux06aJ8IUBg-JvDwAWNbHtlRbZHg"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.70 (Das Skelett, Der Sprengmeister, Prüfungsangst)", "OLAK5uy_mgDpBSiYupfRMMPGqBl-94984jCoY1P9Y"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.71 (Ein seltsamer Bruder, Es war einmal ein Mord, Der Ersatzmann)", "OLAK5uy_nWjqJmTmvTDjPMnb_iUDipd7VJ6kpi44w"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.72 (Der Vertrag, Flugangst, Atemlos)", "OLAK5uy_ljoBiSSasf-EqYwM4KI3VaL-vcPb_ChSA"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.73 (Der Schatz im Silberwald, Die Rentnergang, Der Schrumpfkopf)", "OLAK5uy_ny__EwEDI9b9J1t53MjKKXquXH3_dkuJ8"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.74 (Ein Schluck zuviel, Der Auftrag, Der Klabautermann)", "OLAK5uy_nwXo0AHX-PuAZ4d39VUGmd2ODn5BrM0Lo"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.75 (Die verschwundenen Käfer, Der Mann mit der Maske, Die Expedition)", "OLAK5uy_lesU_LMro6I-jX5p-cfgObPZTkIjKxQwo"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.76 (Der Fotograf, In Vino Veritas, Weidmannsheil)", "OLAK5uy_luPZaxo5kuZKEWGkL-W0xQT4t8SbkyzSA"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.77 (Der Mann ohne Alibi, Der rote Rucksack, Der Traummann)", "OLAK5uy_kB3wWQ6dWK3T54yCDmOk93-gfjGC_Azy4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.78 (Tödlicher Chat, Die Abseitsfalle, Der Schneemann)", "OLAK5uy_kTVz7-roG93QXDZMh-tsgrZqPBYPhzc70"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.79 (Die Armbrust, Der Mann in der Hängematte, Brieffreundschaften)", "OLAK5uy_l7NBTjWPTt365vkDLOkxivhAC_QxhjfrE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.80 (Der geheimnisvolle Schlüssel, Mord auf CD, Zahn um Zahn)", "OLAK5uy_kR-w9OuuAU_hKi7N0BHoxxley2GrU69Dg"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.81 (Der Traumjob, Die Vögel, Geboren am 1. August)", "OLAK5uy_kK-qvgNgOTkplsOTkTShQcJALq0rWdwHo"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.82 (Der Besucher, Die Nichtschwimmer, Die Tankstelle)", "OLAK5uy_mdsGq2jx9C-bPV-ioVmAAYJpG29l23yn0"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.83 (Der Ausserirdische, Der Mann auf der Brücke, Der Regenschirm)", "OLAK5uy_nsmO_7WepOLj_DfkaqYXXW36ZmZk_hN6A"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.84 (Das Haar in der Suppe, Stilleben mit Leiche, Tödliche Fragen)", "OLAK5uy_l20Ursa3fkodfoz_Cifji2PAOuX4BnPf4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.85 (Der Mann am Fenster, Schwarzgeld, Verfolgungswahn)", "OLAK5uy_kNrWufm99tL3Zv4Vop5V9BSJmCI9RemQM"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.86 (Der Balkonmörder, Der letzte Tag, Der unsichtbare Schatz)", "OLAK5uy_m4yo_1iALLoxG7cVosP0vfW2iUon0KWok"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.87 (Der Schuh des Mörders, Die blutigen Kochlöffel, Viel Lärm um nichts)", "OLAK5uy_n1bWwh6h0CcmaqyE6mTtKPiS0bFK5m2JA"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.88 (Der Hausierer, Die Todesanzeige, Wie im Schlaf)", "OLAK5uy_lxLaiSSP6SzGc67UlfTfZwvaSe_3IvCfY"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.89 (Die Politesse, Die Putzfrau, Ein armer Schlucker)", "OLAK5uy_kb9O9i-d40anW8JiGTHdRD4xp1_fpA0MU"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.90 (Der mörderische Reigen, Der Tante-Emma-Laden, Die schwarzen Witwen)", "OLAK5uy_mBMx7Q56v7z7uPDohc2TVUYoqSuX8g3ew"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.91 (Tödliche Kunst, Der Spanner, Die wilde Drei)", "OLAK5uy_nR4zaJ-0e1LMAsQrNm3V1efey0_rSQMiQ"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.92 (Der Biedermann, Der unbekannte Tote, Das Erbe des Herrn Kuhn)", "OLAK5uy_mYXI2GWh9ydO5Ia64gVNzk2xnuHSFhU3s"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.93 (Der gute Zweck, Das Geständnis, Die gestohlene Identität)", "OLAK5uy_kPCC3wcmFhv65w6LLn_gdg6LvlXSOQB9U"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.94 (Tödliches Camping, Die Frau aus Ungarn, Der Stromschlag)", "OLAK5uy_n-krTwIuF3DOiUFqedBLjzIYnr78nzoc4"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.95 (Die rote Lokomotive, Gefährliche Salben, Der Aprilscherz)", "OLAK5uy_lCHfEshgQ_nrPKbYWbcF_hBJTdK7XmAw8"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.96 (Geld oder Leben, Im tiefsten Mittelalter, Tote Liebe)", "OLAK5uy_mEoqlpvdfLjIycT89xtsXiDRl2HmXcbHQ"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.97 (Das geheimnisvolle Haus, Die eiserne Reserve, Die Puppenmacherin)", "OLAK5uy_k95ekJF-tnAmK_jBX4kUDWBHEfWPrL9PY"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.98 (Die Qual der Wahl, Spekulationen, Tödliches Dinner)", "OLAK5uy_m1nig6L9y2zeDKhK47Ot8CUV3se8qxNcw"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.99 (Das Passwort, Der besondere Tag, Die blaue Jacke)", "OLAK5uy_mS7JfH0wBfmVHQC9A9pXxDI7erwbO_lMo"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.100 (Der kleine Bruder, Der Koffer im Schnee, Der letzte Deal)", "OLAK5uy_kgs-dpfCCwTjLGiaUd5drLrImaySWdjyo"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.101 (Die Stimme, Phantomschmerz, Im Schneckentempo)", "OLAK5uy_kkIXEpTqOXTVR8sTsL8ivTPmHR_ecGUg0"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.102 (Das Tattoo, Eiseskälte, Jugendsünden)", "OLAK5uy_m-UutdRwj5EuJ5QqBWpIzYR0mHQGTJzP0"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.103 (Der Fahnder, Der verschwundene Nachbar, Stille Wasser)", "OLAK5uy_kbABxeEe11Vg9sjri--aYhnM7lwPDpK4s"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.104 (Auf Messers Schneide, Schlechtes Timing, Zerstörtes Glück)", "OLAK5uy_nbEb0Ohpl7F0wNEYvYOuDK0AmGXA8PsyY"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.105 (Das zweite Standbein, Der Lauscher, Die Vision)", "OLAK5uy_kmw0dKg2GKcqG56FgJCqUrgG7gDsp8_68"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.106 (Die Beobachter, Die tödliche Kurve, Die tödliche Geschäftsidee)", "OLAK5uy_n7IBFT8ZXzIDlr6Y3eFCGPJcRZGqZ9COc"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.107 (Es geschah am 1. Mai, Die Frau im Keller, Die Erpressung)", "OLAK5uy_lijPcvxTVJhRyb1EjBQhs95x2rXB2qPbE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.108 (Der Jakobsweg, Anti-Aging, Ein Gruss aus Südamerika)", "OLAK5uy_mkuojuF0Vq1ydE3lpaTVHG2AXAMt9XbCI"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.109 (Burnout, Der Parkschein, Das alte Haus)", "OLAK5uy_kiREHJlY_4nWrmFZr7myPzqcTG28gGVBE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.110 (Das Schneeballsystem, Die verschwundene Frau, Der letzte Gang)", "OLAK5uy_loXTGT2_ok8dCS-zsRq2C3siRnO1slohI"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.111 (Die falsche Tochter, Die Heilerin, Die verschwundene Tasche)", "OLAK5uy_nWX9TVefAjBGumT2mXSfXsYbfu10PKGs8"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.112 (Ausser Kontrolle, Der Plan, Die Frau in Rot)", "OLAK5uy_mIaAIVJXaEri8eTndembuoahN-XMPGT50"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.113 (Die Urne, Sturmwarnung, Undercover)", "OLAK5uy_nXjnBpdlxnpopDLHVhdzGtDaJYauF6bVc"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.114 (Das rote Haus, Mitten in der Nacht, Schachmatt)", "OLAK5uy_kGFwPcyAX7BHG89DuX1ojDrHBYCjLkstE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.115 (Das Spukhaus, Der grüne Daumen, Die Paten)", "OLAK5uy_mYxl28Yn0fsaBwB-elw2Ohcru_mQMiaM8"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.116 (Der Schlüssel zum Erfolg, Eine schillernde Frau, Tödliche Koordinaten)", "OLAK5uy_lAe5EowAau0ay9svIut-FmyjfDvCpqigQ"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.117 (Die Drohne, Die Stimme des Täters, Tödliches Start-Up)", "OLAK5uy_nduEYNGMxyyADScv-n8whunuEygUnhQeE"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.118 (Der Mittwochsclub, Der richtige Zeitpunkt, Die gelbe Gefahr)", "OLAK5uy_kQmvvInrl_V9HppBIr4TC_5m1lNnykLLA"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.119 (Mietnomaden, Die Überwachten, Schlank und tot)", "OLAK5uy_k6KPMF0OVZ3-0F_q5KjXAoaDH6yjYUKyk"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.120 (Beste Freunde, Der Lieferwagen, Die perfekte Mischung)", "OLAK5uy_nzg7iNDo3m9GNIFAJ0KO_i0s08OIjoGgs"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.121 (Eine fotogene Leiche, Eine seltsame Erpressung, Gesundheit)", "OLAK5uy_kQQZ2k4mOQj0gqJHqI6bz5Sd7b4R0D1oM"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.122 (Alles unter Kontrolle, Der Hilferuf, Eine seltsame Entführung)", "OLAK5uy_n2Gqw_BaecRO_vSwI18jyidWe--XA6p00"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.123 (Der Mann im Zug, Der Puppensammler, Paranoia)", "OLAK5uy_k2iAvKikGEaQzEa3DGNTtLaRN3XFO7AHo"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.124 (Ein Funken Verstand, Frohe Weihnachten, Superfood)", "OLAK5uy_lvIulwlZTM_x5OsNjn8TEiTcsBtMNZcYc"),
    ("Die haarsträubenden Fälle des Philip Maloney, No.125 (Der Mann auf dem Dach, Die Kochbuchkiller, Im Einkaufswahn)", "OLAK5uy_nd6mNmm7LPLplfXYZwY5XINUesAOv0A_I"),
]
